### ISSUE TITLE
Problema com o "Y"

### ISSUE THREAD

**Issue by igornoberto** [ipea/phonics#4]
GLEYCE ALVES RODRIGUES = LIS ALVS 2DRGS
GLEICE ALVES RODRIGUES = LS ALVS 2DRGS

Todos os Y devem ser trocados por I.

**Comment by igornoberto** [comment]
Segundo a regra fonética (https://sourceforge.net/p/metaphoneptbr/code/ci/master/tree/README), as vogais devem ser mantidas apenas quando no inicio das palavras. E o "Y" deve sempre ser substituído pelo "I". Dessa forma, Gleyce e Gleice seriam, de fato, diferentes.

Vou retirar a regra do Y, mantendo-o apenas se estiver no inicio das palavras como "I".

**Comment by lucasmation** [comment]
Tem q ser igual...
Será q não é sequencial?
Primeiro troca y por i.
Depois retira as vogais

Outra coisa é que se a referência do metaphoneBR que você estiver usando
estiver errada nos não precisamos segui-las



Em 15 de ago de 2017 8:14 AM, "igornoberto" <notifications@github.com>
escreveu:

**Comment by igornoberto** [comment]
@lucasmation 
Não vi nenhuma referencia a ser algo sequencial.
Mas corrigi o problema.

Todas as fontes dirigem às mesmas regras fonéticas, inclusive a citada por Fabio Vaz em https://gitlab.com/IpeaDATA-lab/record_linkage_Brasil/issues/4#note_29708137
