### ISSUE TITLE
Souza x Sousa

### ISSUE THREAD

**Issue by igornoberto** [ipea/phonics#8]
```
> metaphone("sousa souza", language = "pt-br")
[1] "SS SZ"
```

O algoritmo não prevê tal semelhança.

**Comment by lucasmation** [comment]
por mim tem que ser igual sim

2017-08-17 12:57 GMT-03:00 igornoberto <notifications@github.com>:

**Comment by igornoberto** [comment]
fce19dfff12b260f169bc5f62ac0e37c81f05350

**Comment by igornoberto** [comment]
closed this in fe98736
